extends: airbnb-base
env:
  "jest": true
rules:
  # some times next variable is required on express even if it's not used just to specify certain handler functions. So we have to allow it
  no-unused-vars:
    [error, { argsIgnorePattern: next }]
  no-underscore-dangle:
    [error, { allow: ["_id", "__v"] }]
  max-len:
    # keep airbnb's 150 char's per code line but ignore the rule for comments
    [error, { code: 150, ignoreComments: true, ignoreStrings: true, ignoreTemplateLiterals: true }]
  no-plusplus:
    [error, { allowForLoopAfterthoughts: true }]
